/* File: addmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed May 22 09:25:05 2019
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *add_error;
static PyObject *add_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = add_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = add_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(zsubsurf,ZSUBSURF)(double*,double*,double*,int*,int*,int*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** zsubsurf **********************************/
static char doc_f2py_rout_add_zsubsurf[] = "\
zsubsurf(dx,dy,dz,nx,ny,nz,landco,perm,man,ind)\n\nWrapper for ``zsubsurf``.\
\n\nParameters\n----------\n"
"dx : input float\n"
"dy : input float\n"
"dz : input float\n"
"nx : input int\n"
"ny : input int\n"
"nz : input int\n"
"landco : input rank-2 array('d') with bounds (f2py_landco_d0,f2py_landco_d1)\n"
"perm : input rank-3 array('d') with bounds (f2py_perm_d0,f2py_perm_d1,f2py_perm_d2)\n"
"man : input rank-3 array('d') with bounds (f2py_man_d0,f2py_man_d1,f2py_man_d2)\n"
"ind : input rank-3 array('d') with bounds (f2py_ind_d0,f2py_ind_d1,f2py_ind_d2)";
/* extern void F_WRAPPEDFUNC(zsubsurf,ZSUBSURF)(double*,double*,double*,int*,int*,int*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_add_zsubsurf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*,int*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double dx = 0;
  PyObject *dx_capi = Py_None;
  double dy = 0;
  PyObject *dy_capi = Py_None;
  double dz = 0;
  PyObject *dz_capi = Py_None;
  int nx = 0;
  PyObject *nx_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  double *landco = NULL;
  npy_intp landco_Dims[2] = {-1, -1};
  const int landco_Rank = 2;
  PyArrayObject *capi_landco_tmp = NULL;
  int capi_landco_intent = 0;
  PyObject *landco_capi = Py_None;
  double *perm = NULL;
  npy_intp perm_Dims[3] = {-1, -1, -1};
  const int perm_Rank = 3;
  PyArrayObject *capi_perm_tmp = NULL;
  int capi_perm_intent = 0;
  PyObject *perm_capi = Py_None;
  double *man = NULL;
  npy_intp man_Dims[3] = {-1, -1, -1};
  const int man_Rank = 3;
  PyArrayObject *capi_man_tmp = NULL;
  int capi_man_intent = 0;
  PyObject *man_capi = Py_None;
  double *ind = NULL;
  npy_intp ind_Dims[3] = {-1, -1, -1};
  const int ind_Rank = 3;
  PyArrayObject *capi_ind_tmp = NULL;
  int capi_ind_intent = 0;
  PyObject *ind_capi = Py_None;
  int f2py_landco_d0 = 0;
  int f2py_landco_d1 = 0;
  int f2py_perm_d0 = 0;
  int f2py_perm_d1 = 0;
  int f2py_perm_d2 = 0;
  int f2py_man_d0 = 0;
  int f2py_man_d1 = 0;
  int f2py_man_d2 = 0;
  int f2py_ind_d0 = 0;
  int f2py_ind_d1 = 0;
  int f2py_ind_d2 = 0;
  static char *capi_kwlist[] = {"dx","dy","dz","nx","ny","nz","landco","perm","man","ind",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO:add.zsubsurf",\
    capi_kwlist,&dx_capi,&dy_capi,&dz_capi,&nx_capi,&ny_capi,&nz_capi,&landco_capi,&perm_capi,&man_capi,&ind_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dz */
    f2py_success = double_from_pyobj(&dz,dz_capi,"add.zsubsurf() 3rd argument (dz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dx */
    f2py_success = double_from_pyobj(&dx,dx_capi,"add.zsubsurf() 1st argument (dx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dy */
    f2py_success = double_from_pyobj(&dy,dy_capi,"add.zsubsurf() 2nd argument (dy) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ind */
  ;
  capi_ind_intent |= F2PY_INTENT_IN;
  capi_ind_tmp = array_from_pyobj(NPY_DOUBLE,ind_Dims,ind_Rank,capi_ind_intent,ind_capi);
  if (capi_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 10th argument `ind' of add.zsubsurf to C/Fortran array" );
  } else {
    ind = (double *)(PyArray_DATA(capi_ind_tmp));

  /* Processing variable man */
  ;
  capi_man_intent |= F2PY_INTENT_IN;
  capi_man_tmp = array_from_pyobj(NPY_DOUBLE,man_Dims,man_Rank,capi_man_intent,man_capi);
  if (capi_man_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 9th argument `man' of add.zsubsurf to C/Fortran array" );
  } else {
    man = (double *)(PyArray_DATA(capi_man_tmp));

  /* Processing variable nx */
    f2py_success = int_from_pyobj(&nx,nx_capi,"add.zsubsurf() 4th argument (nx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable landco */
  ;
  capi_landco_intent |= F2PY_INTENT_IN;
  capi_landco_tmp = array_from_pyobj(NPY_DOUBLE,landco_Dims,landco_Rank,capi_landco_intent,landco_capi);
  if (capi_landco_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 7th argument `landco' of add.zsubsurf to C/Fortran array" );
  } else {
    landco = (double *)(PyArray_DATA(capi_landco_tmp));

  /* Processing variable perm */
  ;
  capi_perm_intent |= F2PY_INTENT_IN;
  capi_perm_tmp = array_from_pyobj(NPY_DOUBLE,perm_Dims,perm_Rank,capi_perm_intent,perm_capi);
  if (capi_perm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 8th argument `perm' of add.zsubsurf to C/Fortran array" );
  } else {
    perm = (double *)(PyArray_DATA(capi_perm_tmp));

  /* Processing variable ny */
    f2py_success = int_from_pyobj(&ny,ny_capi,"add.zsubsurf() 5th argument (ny) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nz */
    f2py_success = int_from_pyobj(&nz,nz_capi,"add.zsubsurf() 6th argument (nz) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f2py_landco_d0 */
  f2py_landco_d0 = shape(landco, 0);
  /* Processing variable f2py_landco_d1 */
  f2py_landco_d1 = shape(landco, 1);
  /* Processing variable f2py_perm_d0 */
  f2py_perm_d0 = shape(perm, 0);
  /* Processing variable f2py_perm_d1 */
  f2py_perm_d1 = shape(perm, 1);
  /* Processing variable f2py_perm_d2 */
  f2py_perm_d2 = shape(perm, 2);
  /* Processing variable f2py_man_d0 */
  f2py_man_d0 = shape(man, 0);
  /* Processing variable f2py_man_d1 */
  f2py_man_d1 = shape(man, 1);
  /* Processing variable f2py_man_d2 */
  f2py_man_d2 = shape(man, 2);
  /* Processing variable f2py_ind_d0 */
  f2py_ind_d0 = shape(ind, 0);
  /* Processing variable f2py_ind_d1 */
  f2py_ind_d1 = shape(ind, 1);
  /* Processing variable f2py_ind_d2 */
  f2py_ind_d2 = shape(ind, 2);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&dx,&dy,&dz,&nx,&ny,&nz,landco,perm,man,ind,&f2py_landco_d0,&f2py_landco_d1,&f2py_perm_d0,&f2py_perm_d1,&f2py_perm_d2,&f2py_man_d0,&f2py_man_d1,&f2py_man_d2,&f2py_ind_d0,&f2py_ind_d1,&f2py_ind_d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_ind_d2 */
  /* End of cleaning variable f2py_ind_d1 */
  /* End of cleaning variable f2py_ind_d0 */
  /* End of cleaning variable f2py_man_d2 */
  /* End of cleaning variable f2py_man_d1 */
  /* End of cleaning variable f2py_man_d0 */
  /* End of cleaning variable f2py_perm_d2 */
  /* End of cleaning variable f2py_perm_d1 */
  /* End of cleaning variable f2py_perm_d0 */
  /* End of cleaning variable f2py_landco_d1 */
  /* End of cleaning variable f2py_landco_d0 */
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  if((PyObject *)capi_perm_tmp!=perm_capi) {
    Py_XDECREF(capi_perm_tmp); }
  }  /*if (capi_perm_tmp == NULL) ... else of perm*/
  /* End of cleaning variable perm */
  if((PyObject *)capi_landco_tmp!=landco_capi) {
    Py_XDECREF(capi_landco_tmp); }
  }  /*if (capi_landco_tmp == NULL) ... else of landco*/
  /* End of cleaning variable landco */
  } /*if (f2py_success) of nx*/
  /* End of cleaning variable nx */
  if((PyObject *)capi_man_tmp!=man_capi) {
    Py_XDECREF(capi_man_tmp); }
  }  /*if (capi_man_tmp == NULL) ... else of man*/
  /* End of cleaning variable man */
  if((PyObject *)capi_ind_tmp!=ind_capi) {
    Py_XDECREF(capi_ind_tmp); }
  }  /*if (capi_ind_tmp == NULL) ... else of ind*/
  /* End of cleaning variable ind */
  } /*if (f2py_success) of dy*/
  /* End of cleaning variable dy */
  } /*if (f2py_success) of dx*/
  /* End of cleaning variable dx */
  } /*if (f2py_success) of dz*/
  /* End of cleaning variable dz */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of zsubsurf ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"zsubsurf",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(zsubsurf,ZSUBSURF),(f2py_init_func)f2py_rout_add_zsubsurf,doc_f2py_rout_add_zsubsurf},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "add",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_add(void) {
#else
#define RETVAL
PyMODINIT_FUNC initadd(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = add_module = PyModule_Create(&moduledef);
#else
  m = add_module = Py_InitModule("add", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module add (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'add' is auto-generated with f2py (version:2).\nFunctions:\n"
"  zsubsurf(dx,dy,dz,nx,ny,nz,landco,perm,man,ind)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  add_error = PyErr_NewException ("add.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

    {
      extern void F_FUNC(zsubsurf,ZSUBSURF)(void);
      PyObject* o = PyDict_GetItemString(d,"zsubsurf");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(zsubsurf,ZSUBSURF),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("zsubsurf"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("zsubsurf"));
#endif
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"add");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
