C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapzsubsurf (dx, dy, dz, nx, ny, nz, landco,
     & perm, man, ind, f2py_landco_d0, f2py_landco_d1, f2py_perm_d0, f2p
     &y_perm_d1, f2py_perm_d2, f2py_man_d0, f2py_man_d1, f2py_man_d2, f2
     &py_ind_d0, f2py_ind_d1, f2py_ind_d2)
      double precision dx
      double precision dy
      double precision dz
      integer nx
      integer ny
      integer nz
      integer f2py_landco_d0
      integer f2py_landco_d1
      integer f2py_perm_d0
      integer f2py_perm_d1
      integer f2py_perm_d2
      integer f2py_man_d0
      integer f2py_man_d1
      integer f2py_man_d2
      integer f2py_ind_d0
      integer f2py_ind_d1
      integer f2py_ind_d2
      double precision landco(f2py_landco_d0,f2py_landco_d1)
      double precision perm(f2py_perm_d0,f2py_perm_d1,f2py_perm_d2
     &)
      double precision man(f2py_man_d0,f2py_man_d1,f2py_man_d2)
      double precision ind(f2py_ind_d0,f2py_ind_d1,f2py_ind_d2)
      interface
      subroutine zsubsurf(dx,dy,dz,nx,ny,nz,landco,perm,man,ind) 
          double precision :: dx
          double precision :: dy
          double precision :: dz
          integer :: nx
          integer :: ny
          integer :: nz
          double precision, allocatable,dimension(:,:) :: landco
          double precision, allocatable,dimension(:,:,:) :: perm
          double precision, allocatable,dimension(:,:,:) :: man
          double precision, allocatable,dimension(:,:,:) :: ind
      end subroutine zsubsurf
      end interface
      call zsubsurf(dx, dy, dz, nx, ny, nz, landco, perm, man, ind
     &)
      end

